### ISSUE TITLE
测试发现MarkDown类型不能@人

### ISSUE THREAD

**Issue by pythonohtyp** [CatchZeng/dingtalk#10]
`package main

import (
	"fmt"

	"github.com/CatchZeng/dingtalk/pkg/dingtalk"
)

func main() {
	accessToken := "xxxxxxxxxxx"
	secret := "xxxxxxxxxxxxxxxxxxxxx0279c94f59fdbc3650"
	client := dingtalk.NewClient(accessToken, secret)

	msg := dingtalk.NewMarkdownMessage().SetMarkdown("这是TITLE","测试文本").SetAt([]string{"158XXXXX46"}, false)
	_, _, _ = client.Send(msg)
}`

**Comment by arden** [comment]
我刚测试了一下，也是不行，刚好你就提了这个bug。

**Comment by pythonohtyp** [comment]
是的，直接用官方的curl请求，好像也不行

**Comment by CatchZeng** [comment]
如果官网的也不行的话，那本库也没办法了

**Comment by doubility** [comment]
消息文本中也需要@人
`msg := dingtalk.NewMarkdownMessage().SetMarkdown("这是TITLE","测试文本@158XXXXX46").SetAt([]string{"158XXXXX46"}, false)
_, _, _ = client.Send(msg)`

**Comment by pythonohtyp** [comment]
@doubility 好的，谢谢，是我没看特殊说明，按你的测试可以的。
