### ISSUE TITLE
markdown 如何换行呢，换不了行诶

### ISSUE THREAD

**Issue by Marerc** [CatchZeng/dingtalk#17]
我在命令行里这样写：

```shell
dingtalk actionCard -t ${ACCESS_TOKEN} -s ${SECRET} -i xxxxx已部署测试 -b 下载
 -c http://172.16.58.16:8001/development/latest.tar.gz -e "# xxxxx已部署 \n\n http:
//baidu.com"
```

在钉钉里收到的是这样的，并没有换行：

**Comment by AaronLianS** [comment]
dingtalk actionCard -t ${ACCESS_TOKEN} -s ${SECRET} -i xxxxx已部署测试 -b 下载
 -c http://172.16.58.16:8001/development/latest.tar.gz -e "# xxxxx已部署

http://baidu.com"
直接这样就行了。

**Comment by Marerc** [comment]
> dingtalk actionCard -t ${ACCESS_TOKEN} -s ${SECRET} -i xxxxx已部署测试 -b 下载 -c http://172.16.58.16:8001/development/latest.tar.gz -e "# xxxxx已部署
> 
> http://baidu.com" 直接这样就行了。

CI 文件里这样写不了，cli可以

**Comment by Marerc** [comment]
好吧
