### ISSUE TITLE
go get有问题

### ISSUE THREAD

**Issue by Billdex** [CatchZeng/dingtalk#5]
go get得到的内容与github仓库实际内容不一样
![image](https://user-images.githubusercontent.com/23182543/93072980-c782b680-f6b4-11ea-8197-01042bb37897.png)

**Comment by Billdex** [comment]
指定v2.1.0失败，只能指定master才能正确拉取

**Comment by CatchZeng** [comment]
已修复，忘了 go 版本的处理方式了，感谢提醒。

现在把最新版本改成 v1.2.0 了，你可以试下，还不行的话，你可以加 -u

```shell
❯ go get -u github.com/CatchZeng/dingtalk
```

验证 test

```shell
❯ go mod init test
go: creating new go.mod: module test
❯ go get github.com/CatchZeng/dingtalk
go: extracting github.com/CatchZeng/dingtalk v1.2.0
```
