### ISSUE TITLE
markdown 会转为纯文本，不显示效果

### ISSUE THREAD

**Issue by pc10201** [CatchZeng/dingtalk#8]
markdown -i "title" -e "#### 杭 州天气  \n > 9度"

标题换行都不会显示

**Comment by CatchZeng** [comment]
命令行输入的会被转义，你直接换行（不要用 \n），就可以显示了。

可以参考 demo <https://github.com/CatchZeng/dingtalk#demo>

另外，你可以在新的版本中，使用  -D 参数，查看下实际发送的消息内容，调试的时候可以方便些
